version: "3.8"

services: 
  server:
    image: 'nginx:stable-alpine'
    ports: 
      - '8090:80'
    volumes: 
      - ./:/var/www/html
      - ./service-config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: 
      - php
      - db
  php:
    build: 
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes: 
      - ./:/var/www/html:delegated 
  db:
    image: mariadb:10.3
    ports: 
      - '3306:3306'
    env_file: 
      - ./service-config/env/mariadb.env
    volumes:
      - ./dbdata:/var/lib/mysql
  mail:
    image: 'reachfive/fake-smtp-server'
    ports: 
      - '1090:1080'
  composer:
    build: 
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes: 
      - ./:/var/www/html
  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes: 
      - ./:/var/www/html